
CREATE TABLE dbfreightech.BENEFICIOS_EQUIPE_ENTREGA_ROTA 
( id INT(10) NOT NULL AUTO_INCREMENT , 
VIGENCIA VARCHAR(250) NULL ,
UNIDADE_CNPJ VARCHAR(250) NULL ,
UNIDADE_NOME VARCHAR(250) NULL ,
UNIDADE_SAP VARCHAR(250) NULL ,
UNIDADE_TMS VARCHAR(250) NULL ,
UNIDADE_PROMAX_UNB VARCHAR(250) NULL ,
UNIDADE_REGIONAL VARCHAR(250) NULL ,
OPERADOR_CNPJ VARCHAR(250) NULL ,
OPERADOR_NOME VARCHAR(250) NULL ,
OPERADOR_SAP VARCHAR(250) NULL ,
OPERADOR_TMS VARCHAR(250) NULL ,
OPERADOR_PROMAX VARCHAR(250) NULL ,
ORGANIZACAO_DE_COMPRAS VARCHAR(250) NULL ,
PRAZO_PAGAMENTO VARCHAR(250) NULL ,
BENEFICIO VARCHAR(250) NULL ,
CARGO VARCHAR(250) NULL ,
TOTAL_BENEFICIO VARCHAR(250) NULL ,
TURNO VARCHAR(250) NULL ,
PERMITIR_CALCULO_PROPORCIONAL VARCHAR(250) NULL ,
_ID VARCHAR(250) NULL ,
 PRIMARY KEY (`ID`)) ENGINE = InnoDB;
ALTER TABLE `dbfreightech`.`BENEFICIOS_EQUIPE_ENTREGA_ROTA` ADD UNIQUE `UNI_ID` (`UNIDADE_NOME`, `_ID`); 
ALTER TABLE `BENEFICIOS_EQUIPE_ENTREGA_ROTA` ADD INDEX( `UNIDADE_NOME`);
ALTER TABLE `BENEFICIOS_EQUIPE_ENTREGA_ROTA` ADD INDEX( `_ID`);
