CREATE TABLE BENEFICIO_EQUIPE_ARMAZEM
(
    ID INT(10) NOT NULL AUTO_INCREMENT,
    VIGENCIA VARCHAR(250) NULL,
    UNIDADE_CNJP VARCHAR(250) NULL,
    UNIDADE_NOME VARCHAR(250) NULL,
    UNIDADE_SAP VARCHAR(250) NULL,
    UNIDADE_TMS VARCHAR(250) NULL,
    UNIDADE_PROMAX_UNB VARCHAR(250) NULL,
    UNIDADE_REGIONAL VARCHAR(250) NULL,
    OPERADOR_CNPJ VARCHAR(250) NULL,
    OPERADOR_NOME VARCHAR(250) NULL,
    OPERADOR_SAP VARCHAR(250) NULL,
    OPERADOR_TMS VARCHAR(250) NULL,
    OPERADOR_PROMAX VARCHAR(250) NULL,
    ORGANIZACAO_DE_COMPRAS VARCHAR(250) NULL,
    PRAZO_PAGAMENTO VARCHAR(250) NULL,
    CARGOBENEFICIOAPOIO VARCHAR(250) NULL,
    ITEMBENEFICIO VARCHAR(250) NULL,
    PARTICIPACAOEMPRESA VARCHAR(250) NULL,
    PERMITIRCALCULOPROPORCIONAL VARCHAR(250) NULL,
    QUANTIDADE VARCHAR(250) NULL,
    QUANTIDADEDIASUTEIS VARCHAR(250) NULL,
    RESSARCIMENTOFUNCIONARIO VARCHAR(250) NULL,
    TOTAL VARCHAR(250) NULL,
    VALOR VARCHAR(250) NULL,
    _ID VARCHAR(250) NULL,
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;
ALTER TABLE `BENEFICIO_EQUIPE_ARMAZEM` ADD UNIQUE `UNI_ID` (`UNIDADE_NOME`, `_ID`);
ALTER TABLE `BENEFICIO_EQUIPE_ARMAZEM` ADD INDEX( `UNIDADE_NOME`);
ALTER TABLE `BENEFICIO_EQUIPE_ARMAZEM` ADD INDEX( `_ID`);
