CREATE TABLE QLP_ADM_ARMAZEM
(
    ID INT(10) NOT NULL AUTO_INCREMENT,
    VIGENCIA VARCHAR(250) NULL,
    UNIDADE_CNJP VARCHAR(250) NULL,
    UNIDADE_NOME VARCHAR(250) NULL,
    UNIDADE_SAP VARCHAR(250) NULL,
    UNIDADE_TMS VARCHAR(250) NULL,
    UNIDADE_PROMAX_UNB VARCHAR(250) NULL,
    UNIDADE_REGIONAL VARCHAR(250) NULL,
    OPERADOR_CNPJ VARCHAR(250) NULL,
    OPERADOR_NOME VARCHAR(250) NULL,
    OPERADOR_SAP VARCHAR(250) NULL,
    OPERADOR_TMS VARCHAR(250) NULL,
    OPERADOR_PROMAX VARCHAR(250) NULL,
    ORGANIZACAO_DE_COMPRAS VARCHAR(250) NULL,
    PRAZO_PAGAMENTO VARCHAR(250) NULL,
    CARGO VARCHAR(250) NULL,
    DESPESA_BENEFICIO VARCHAR(250) NULL,
    DESPESA_ENCARGOS VARCHAR(250) NULL,
    DESPESA_FROTA_LEVE VARCHAR(250) NULL,
    DESPESA_ORDENADOS VARCHAR(250) NULL,
    DESPESA_TELEFONIA VARCHAR(250) NULL,
    DESPESA_UNIFORMES VARCHAR(250) NULL,
    QUANTIDADE_BENEFICIO VARCHAR(250) NULL,
    QUANTIDADE_ENCARGOS VARCHAR(250) NULL,
    QUANTIDADE_FROTA_LEVE VARCHAR(250) NULL,
    QUANTIDADE_ORDENADOS VARCHAR(250) NULL,
    QUANTIDADE_TELEFONIA VARCHAR(250) NULL,
    QUANTIDADE_UNIFORMES VARCHAR(250) NULL,
    SALARIO_ENCARGOS VARCHAR(250) NULL,
    SALARIO_ORDENADOS VARCHAR(250) NULL,
    VALE_TRANSPORTE VARCHAR(250) NULL,
    VALOR_BENEFICIO VARCHAR(250) NULL,
    VALOR_FROTA_LEVE VARCHAR(250) NULL,
    VALOR_TELEFONIA VARCHAR(250) NULL,
    VALOR_UNIFORMES VARCHAR(250) NULL,
    VALETRANSPORTERESSARCIMENTO VARCHAR(250) NULL,
    VALETRANSPORTEVALORES VARCHAR(250) NULL,
    _ID VARCHAR(250) NULL,
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;
ALTER TABLE `QLP_ADM_ARMAZEM` ADD UNIQUE `UNI_ID` (`UNIDADE_NOME`, `_ID`);
ALTER TABLE `QLP_ADM_ARMAZEM` ADD INDEX( `UNIDADE_NOME`);
ALTER TABLE `QLP_ADM_ARMAZEM` ADD INDEX( `_ID`);


Vigencia	Unidade - CNPJ	Unidade - Nome	Unidade SAP	Unidade TMS	Unidade - Promax UNB	Unidade - Regional	Operador - CNPJ	Operador - Nome	Operador - SAP	Operador - TMS	Operador - Promax	Organizacao de Compras	Prazo Pagamento	descricaoDespesa	quantidade	valorTotal	valorUnitario	_id
